## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This needs to be changed accordingly to the application for what localsearch
# is bundled. As of F43, this domain is hard-coded in the binary at build time
# and is no longer configurable at post-install.  gnome-music is the only
# currently maintained app which absolutely requires localsearch, so this is
# built just for that.  If more apps need support, then we will need more
# creative solutions.
%if 0%{?flatpak}
%global domain_ontology org.gnome.Music
%else
%global domain_ontology org.freedesktop
%endif

%global with_enca 1
%global with_ffmpeg 1
%global with_libcue 1
%global with_libmediainfo 1
%global with_totem_pl_parser 1

%if 0%{?rhel}
%global with_enca 0
%global with_ffmpeg 0
%global with_libcue 0
%global with_libmediainfo 0
%if 0%{?rhel} >= 10
%global with_totem_pl_parser 0
%endif
%endif

%global tinysparql_version 3.11

%global systemd_units localsearch-3.service localsearch-control-3.service localsearch-writeback-3.service

# Exclude private libraries from autogenerated provides and requires
%global __provides_exclude_from ^%{_libdir}/localsearch-3.0/
%global __requires_exclude ^(libtracker-extract\.so|libtracker-extract-zip\.so|libextract-.*\.so|libwriteback-.*\.so)

Name:           localsearch
Version:        3.12~rc
Release:        %autorelease
Summary:        Localsearch and metadata extractors

# The indexer is a mix of GPLv2 and LGPLv2+ code
License:        GPL-2.0-or-later AND LGPL-2.1-or-later
URL:            https://gnome.pages.gitlab.gnome.org/localsearch/
Source0:        https://download.gnome.org/sources/%{name}/%{gnome_major_minor_version}/%{name}-%{gnome_tarball_version}.tar.xz

%gnome_check_version

BuildRequires:  asciidoc
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  giflib-devel
BuildRequires:  meson
BuildRequires:  systemd-rpm-macros
BuildRequires:  pkgconfig(dbus-1)
%if 0%{?with_enca}
BuildRequires:  pkgconfig(enca)
%endif
BuildRequires:  pkgconfig(exempi-2.0)
BuildRequires:  pkgconfig(flac)
BuildRequires:  pkgconfig(gexiv2-0.16)
BuildRequires:  pkgconfig(gobject-introspection-1.0)
BuildRequires:  pkgconfig(gstreamer-1.0)
BuildRequires:  pkgconfig(gstreamer-pbutils-1.0)
BuildRequires:  pkgconfig(gstreamer-tag-1.0)
BuildRequires:  pkgconfig(icu-i18n)
BuildRequires:  pkgconfig(icu-uc)
%if 0%{?with_ffmpeg}
BuildRequires:  pkgconfig(libavformat)
%endif
%if 0%{?with_libcue}
BuildRequires:  pkgconfig(libcue)
%endif
BuildRequires:  pkgconfig(libexif)
BuildRequires:  pkgconfig(libgsf-1)
BuildRequires:  pkgconfig(libgxps)
BuildRequires:  pkgconfig(libjpeg)
%if 0%{?with_libmediainfo}
BuildRequires:  pkgconfig(libmediainfo)
%endif
BuildRequires:  pkgconfig(libpng)
BuildRequires:  pkgconfig(libseccomp)
BuildRequires:  pkgconfig(libtiff-4)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(libzip)
BuildRequires:  pkgconfig(poppler-glib)
%if 0%{?with_totem_pl_parser}
BuildRequires:  pkgconfig(totem-plparser)
%endif
BuildRequires:  pkgconfig(tinysparql-3.0) >= %{tinysparql_version}
BuildRequires:  pkgconfig(vorbisfile)
%if !0%{?flatpak}
BuildRequires:  pkgconfig(libosinfo-1.0)
BuildRequires:  pkgconfig(libnm)
BuildRequires:  pkgconfig(upower-glib)
%endif
BuildRequires:  python3-dbusmock

# renamed in F42
Obsoletes:      tracker-miners < 3.8
Provides:       tracker-miners = %{version}-%{release}
Provides:       tracker-miners%{?_isa} = %{version}-%{release}

%description
Tinysparql is a powerful desktop-neutral first class object database,
tag/metadata database and search tool.

This package contains various miners and metadata extractors for tinysparql.


%prep
%autosetup -p1 -n %{name}-%{gnome_tarball_version}


%build
%meson \
%if 0%{?flatpak}
  -Dwriteback=false \
  -Dsystemd_user_services=false \
  -Diso=disabled \
  -Dbattery_detection=none \
  -Ddomain_prefix=%{domain_ontology} \
%endif
%if ! 0%{?with_libcue}
  -Dcue=disabled \
%endif
%if ! 0%{?with_ffmpeg}
  -Dlibav=disabled \
%endif
%if ! 0%{?with_libmediainfo}
  -Dlibmediainfo=disabled \
%endif
%if ! 0%{?flatpak}
  -Dsystemd_user_services_dir=%{_userunitdir} \
%endif
%if ! 0%{?with_totem_pl_parser}
  -Dplaylist=disabled \
%endif
  %{nil}

%meson_build


%install
%meson_install

%find_lang localsearch3


%post
%systemd_user_post %{systemd_units}

%preun
%systemd_user_preun %{systemd_units}

%postun
%systemd_user_postun_with_restart %{systemd_units}


%files -f localsearch3.lang
%license COPYING*
%doc AUTHORS NEWS README.md
%config(noreplace) %{_sysconfdir}/xdg/autostart/localsearch-3.desktop
%{_bindir}/localsearch
%{_libdir}/localsearch-3.0/
%{_libexecdir}/localsearch-3
%{_libexecdir}/localsearch-control-3
%{_libexecdir}/localsearch-extractor-3
%{_libexecdir}/localsearch-endpoint-3
%if ! 0%{?flatpak}
%{_libexecdir}/localsearch-writeback-3
%endif
%dir %{_datadir}/bash-completion
%dir %{_datadir}/bash-completion/completions
%{_datadir}/bash-completion/completions/localsearch
%dir %{_datadir}/dbus-1
%dir %{_datadir}/dbus-1/interfaces
%dir %{_datadir}/dbus-1/services
%{_datadir}/dbus-1/interfaces/org.freedesktop.Tracker3.Miner.Files.Index.xml
%{_datadir}/dbus-1/interfaces/org.freedesktop.Tracker3.Miner.xml
%{_datadir}/dbus-1/services/%{domain_ontology}.LocalSearch3.*
%{_datadir}/dbus-1/services/%{domain_ontology}.Tracker3.*
%if 0%{?flatpak}
%exclude %{_datadir}/dbus-1/services/org.freedesktop.LocalSearch3.service
%exclude %{_datadir}/dbus-1/services/org.freedesktop.Tracker3.Miner.Files.service
%endif
%{_datadir}/glib-2.0/schemas/*
%{_datadir}/localsearch3/
%{_mandir}/man1/localsearch*.1*
%if !0%{?flatpak}
%{_userunitdir}/localsearch*.service
%endif


%changelog
## START: Generated by rpmautospec
* Tue Sep 01 2026 Milan Crha <mcrha@redhat.com> - 3.12~rc-1
- Update to 3.12.rc

* Mon Aug 03 2026 Jan Grulich <jgrulich@redhat.com> - 3.12~beta-1
- Update to 3.12.beta

* Thu Jul 16 2026 Fedora Release Engineering <releng@fedoraproject.org> - 3.12~alpha-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_45_Mass_Rebuild

* Thu Jul 09 2026 Yaakov Selkowitz <yselkowi@redhat.com> - 3.12~alpha-2
- Allow for disabling libmediainfo

* Mon Jun 29 2026 Milan Crha <mcrha@redhat.com> - 3.12~alpha-1
- Update to 3.12.alpha

* Wed May 27 2026 František Zatloukal <fzatlouk@redhat.com> - 3.11.1-2
- Rebuilt for icu 78.3

* Mon Apr 20 2026 Milan Crha <mcrha@redhat.com> - 3.11.1-1
- Update to 3.11.1

* Wed Mar 25 2026 Jan Grulich <jgrulich@redhat.com> - 3.11.0-5
- Add configuration for release-monitoring

* Tue Mar 24 2026 Milan Crha <mcrha@redhat.com> - 3.11.0-4
- Exclude internal libtracker-extract-zip.so from Requires

* Tue Mar 24 2026 Milan Crha <mcrha@redhat.com> - 3.11.0-3
- Add a patch to fix a crash in 3.11.0

* Mon Mar 16 2026 Milan Crha <mcrha@redhat.com> - 3.11.0-1
- Update to 3.11.0

* Tue Mar 03 2026 Jan Grulich <jgrulich@redhat.com> - 3.11~rc-1
- Update to 3.11.rc

* Mon Mar 02 2026 Jan Grulich <jgrulich@redhat.com> - 3.11~beta-4
- Packit: drop upstream_project_url and rely on release-monitoring only

* Wed Feb 25 2026 Jan Grulich <jgrulich@redhat.com> - 3.11~beta-3
- Packit: drop fast_forward_merge_into as current stable branches diverge

* Tue Feb 24 2026 Jan Grulich <jgrulich@redhat.com> - 3.11~beta-2
- Onboard to Packit for stable Fedora branches

* Mon Feb 23 2026 Jan Grulich <jgrulich@redhat.com> - 3.11~beta-1
- Update to 3.11~beta

* Fri Feb 13 2026 Michael Catanzaro <mcatanzaro@gnome.org> - 3.11~alpha-6
- Add relative symlink path and remove workaround from spec file

* Thu Feb 12 2026 Yaakov Selkowitz <yselkowi@redhat.com> - 3.11~alpha-5
- Drop obsolete libiptcdata dependency

* Fri Jan 30 2026 Jan Horak <jhorak@redhat.com> - 3.11~alpha-4
- Use newer libgexiv2-0.16

* Wed Jan 21 2026 Jan Horak <jhorak@redhat.com> - 3.11~alpha-1
- Update to 3.11~alpha

* Fri Jan 16 2026 Fedora Release Engineering <releng@fedoraproject.org> - 3.10.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Thu Dec 11 2025 Adrian Vovk <adrianvovk@gmail.com> - 3.10.2-1
- Update to 3.10.2

* Mon Nov 10 2025 Yaakov Selkowitz <yselkowi@redhat.com> - 3.10.1-3
- Update flatpak configuration

* Wed Oct 15 2025 Dominik 'Rathann' Mierzejewski <dominik@greysector.net> - 3.10.1-2
- Rebuilt for FFmpeg 8

* Tue Oct 14 2025 Petr Schindler <pschindl@redhat.com> - 3.10.1-1
- Update to 3.10.1

* Sun Oct 12 2025 Yaakov Selkowitz <yselkowi@redhat.com> - 3.10.0-3
- Fix RPM absolute symlink warning for flatpak builds

* Tue Sep 16 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 3.10.0-2
- Fix RPM absolute symlink warning

* Tue Sep 16 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 3.10.0-1
- Update to 3.10.0

* Tue Sep 16 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 3.10~rc-2
- Remove forgotten patch

* Thu Sep 04 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 3.10~rc-1
- Update to 3.10.rc

* Fri Aug 29 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 3.10~beta-3
- Fix changelog and switch to %%autorelease

* Wed Aug 06 2025 František Zatloukal <fzatlouk@redhat.com> - 3.10~beta-2
- Rebuilt for icu 77.1

* Tue Aug 05 2025 nmontero <nmontero@redhat.com> - 3.10~beta-1
- Update to 3.10.beta

* Thu Jul 24 2025 Fedora Release Engineering <releng@fedoraproject.org> - 3.10~alpha-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Wed Jul 09 2025 Milan Crha <mcrha@redhat.com> - 3.10~alpha-1
- Update to 3.10.alpha

* Tue Mar 25 2025 Yaakov Selkowitz <yselkowi@redhat.com> - 3.9.0-2
- Fix flatpak build

* Wed Mar 19 2025 nmontero <nmontero@redhat.com> - 3.9.0-1
- Update to 3.9.0

* Tue Mar 04 2025 Yaakov Selkowitz <yselkowi@redhat.com> - 3.9~rc-2
- Disable ffmpeg dependency on RHEL

* Mon Mar 03 2025 nmontero <nmontero@redhat.com> - 3.9~rc-1
- Update to 3.9.rc

* Thu Feb 06 2025 nmontero <nmontero@redhat.com> - 3.8~rc-12
- Rebuild for the renaming of tracker to tinysparql

* Tue Feb 04 2025 nmontero <nmontero@redhat.com> - 3.8~rc-11
- Version bump

* Tue Feb 04 2025 nmontero <nmontero@redhat.com> - 3.8~rc-10
- Bump the version of the tracker-miners obsoletes

* Wed Jan 29 2025 nmontero <nmontero@redhat.com> - 3.8~rc-9
- Delete a Requires line

* Fri Jan 24 2025 nmontero <nmontero@redhat.com> - 3.8~rc-8
- Change in Requires

* Mon Jan 20 2025 nmontero <nmontero@redhat.com> - 3.8~rc-7
- Add missing patch file

* Mon Jan 20 2025 Fedora Release Engineering <releng@fedoraproject.org> - 3.8~rc-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Fri Jan 17 2025 Fedora Release Engineering <releng@fedoraproject.org> - 3.8~rc-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Fri Jan 17 2025 nmontero <nmontero@redhat.com> - 3.8~rc-4
- Add gcc patch

* Wed Jan 15 2025 nmontero <nmontero@redhat.com> - 3.8~rc-3
- Bump release to rebuild after deleted build

* Thu Nov 21 2024 nmontero <nmontero@redhat.com> - 3.8~rc-2
- Add missing file

* Tue Nov 19 2024 nmontero <nmontero@redhat.com> - 3.8~rc-1
- Rename tracker-miners to localsearch
## END: Generated by rpmautospec
